  [[redirects]]
  from = "/node/references/clouds/*"
  to = "/node/how-to-guides/clouds/:splat"

  from = "/rails/references/clouds/*"
  to = "/rails/how-to-guides/clouds/:splat"

  from = "/maestro/references/clouds/*"
  to = "/maestro/how-to-guides/clouds/:splat"
  